### ISSUE TITLE
短信发送偶现异常：Load Json File Error

### ISSUE THREAD

**Issue by jiniannet** [aliyun/aliyun-openapi-net-sdk#338]
dotnet 版本：2.2
平台：Windows
产品名称：短信
产品版本：aliyun-net-sdk-core.dll  1.5.1.0

出错代码
`
            CommonRequest request = new CommonRequest();
            request.Method = MethodType.POST;
            request.Domain =  "dysmsapi.aliyuncs.com";
            request.Version =  "2017-05-25";
            request.Action = "SendBatchSms";
            request.QueryParameters["PhoneNumberJson"] = $"[\"150xxxxxxxx\"]";
            request.QueryParameters["SignNameJson"] = $"[\"XXX\"]"; 
            request.QueryParameters["TemplateCode"] =“xxxx”;
            request.QueryParameters["TemplateParamJson"] = $"[1234]";
            var response = client.GetCommonResponse(request); //这一句出错

`
ERROR

> 
Load Json File Error : System.ArgumentNullException: Value cannot be null.
Parameter name: propertyName
   at Newtonsoft.Json.Linq.JObject.get_Item(String propertyName)
   at Aliyun.Acs.Core.Retry.Util.LoadFromJsonFile.GetRetryableApiList(String product, String version, String sectionName)
t exception_stacktrace 	
	   at Aliyun.Acs.Core.Retry.Util.LoadFromJsonFile.GetRetryableApiList(String product, String version, String sectionName)
   at Aliyun.Acs.Core.Retry.Condition.RetryOnApiCondition.ShouldRetry(RetryPolicyContext retryPolicyContext)
   at Aliyun.Acs.Core.Retry.Condition.OrRetryCondition.ShouldRetry(RetryPolicyContext retryPolicyContext)
   at Aliyun.Acs.Core.Retry.Condition.AndRetryCondition.ShouldRetry(RetryPolicyContext retryPolicyContext)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, String regionId, AlibabaCloudCredentials credentials, Signer signer, Nullable`1 format, List`1 endpoints)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, IClientProfile profile)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request)
   at Aliyun.Acs.Core.DefaultAcsClient.GetCommonResponse(CommonRequest request)

有一定几率出现，有可能是HTTP ERROR 没有正常处理

**Comment by liaoyustudent** [comment]
您好，请通过 `nuget` 安装最新的 `aliyun-net-sdk-core` version `1.5.4` .

**Comment by JacksonTian** [comment]
@jiniannet 请问有没有解决您的问题？

这个 Issue 我们暂时先关闭了。如果您仍然有问题，请重新打开。
